name: golden_toolkit
description: Common patterns for screenshot-based widget testing using Goldens.
version: 0.16.0
homepage: https://github.com/sncf-connect-tech/flutter_glove_box/
repository: https://github.com/sncf-connect-tech/flutter_glove_box/tree/master
issue_tracker: https://github.com/sncf-connect-tech/flutter_glove_box/issues
publish_to:

environment:
  sdk: ">=2.18.4 <4.0.0"
  flutter: ^3.29.3

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^6.0.0
  sample_dependency:
    path: test/sample_dependency
  test_api: ^0.7.6

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/fonts/Roboto-Regular.ttf
