name: golden_toolkit
description: Common patterns for screenshot-based widget testing using Goldens.
version: 0.15.0
homepage: https://github.com/sncf-connect-tech/flutter_glove_box/
repository: https://github.com/sncf-connect-tech/flutter_glove_box/tree/master
issue_tracker: https://github.com/sncf-connect-tech/flutter_glove_box/issues

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  collection: ^1.19.1

dev_dependencies:
  flutter_lints: ^2.0.1
  sample_dependency:
    path: test/sample_dependency
  test_api: ^0.4.12

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/fonts/Roboto-Regular.ttf
